module.exports = {
    "PRESS": [
        "PRESS UNILATERAL DE PÉ COM KTB",
        "PRESS UNILATERAL SPLIT COM KTB",
        "PRESS UNILATERAL SENTADO COM KTB",
        "PRESS BILATERAL SEMI-AJOELHADO COM KTB",
        "PRESS BILATERAL AJOELHADO COM KTB",
        "PRESS BILATERAL DE PÉ COM KTB",
        "PRESS BILATERAL SPLIT COM KTB",
        "PRESS BILATERAL SENTADO COM KTB",
        "PRESS SEMI-AJOELHADO COM BARRA",
        "PRESS AJOELHADO COM BARRA",
        "PRESS DE PÉ COM BARRA",
        "PRESS SPLIT COM BARRA",
        "PRESS SENTADO COM BARRA",
        "PRESS LANDMINE UNILATERAL SEMI-AJOELHADO",
        "PRESS LANDMINE UNILATERAL AJOELHADO",
        "PRESS LANDMINE UNILATERAL DE PÉ",
        "PRESS LANDMINE UNILATERAL SPLIT",
        "PRESS LANDMINE UNILATERAL BASE UNIPODAL",
        "PRESS LANDMINE BILATERAL SEMI-AJOELHADO",
        "PRESS LANDMINE BILATERAL AJOELHADO",
        "PRESS LANDMINE BILATERAL DE PÉ",
        "PRESS LANDMINE BILATERAL SPLIT",
        "PRESS LANDMINE BILATERAL BASE UNIPODAL"
    ],
    "OMBRO LATERAL": [
        "OMBRO LATERAL"
    ],
    "OMBRO FRONTAL": [
        "OMBRO FRONTAL"
    ],
    "PARALELA": [
        "PARALELA"
    ]
};
