module.exports = {
    "BARRA FIXA": [
        "BARRA FIXA",
        "BARRA FIXA COMPLETA"
    ],
    "PUXADA NA POLIA": [
        "PUXADA NA POLIA UNILATERAL SENTADO",
        "PUXADA NA POLIA UNILATERAL AJOLEHADO",
        "PUXADA NA POLIA BILATERAL AJOELHADO",
        "PUXADA NA POLIA UNILATERAL DE PÉ",
        "PUXADA NA POLIA BILATERAL DE PÉ"
    ]
};
