module.exports = [
    "PISTOL",
    "AGACHAMENTO UNILATERAL SENTANDO E LEVANDO DO BANCO",
    "AGACHAMENTO UNILATERAL SENTANDO E LEVANDO DO BANCO LEVANDO O PESO À FRENTE",
    "AGACHAMENTO UNI EM CIMA DO STEP  LEVANDO O PESO À FRENTE",
    "AGACHAMENTO UNI EM CIMA DA CAIXA LEVANDO O PESO À FRENTE",
    "AGACHAMENTO UNI EM CIMA DA CAIXA GOBLET",
    "AGACHAMENTO UNI EM CIMA DA CAIXA KBT RACK",
    "SKATER SQUAT LEVANDO O PESO À FRENTE",
    "BÚLGARO",
    "BÚLGARO GOBLET",
    "BÚLGARO + HALTER BILATERAL",
    "BÚLGARO + HALTER UNILATERAL",
    "BÚLGARO + BARRA HEXAGONAL",
    "BÚLGARO + BARRA NAS COSTAS"
];
