module.exports = {
    sumo: [
        "SUNO BARRA",
        "SUNO HALTER"
    ],
    agachamento: [
        "AGACHAMENTO PASSADA LATERAL",
        "AGACHAMENTO LATERAL",
        "AGACHAMENTO LATERAL DINAMICO",
        "AGACHAMENTO TRILA EXTENSÃO",
        "AGACHAMENTO GILBERT",
        "AGACHAMENTO LEVANDO AS MÃOS À FRENTE",
        "AGACHAMENTO BARRA NAS COSTAS",
        "AGACHAMENTO BARRA NA FRENTE",
        "AGACHAMENTO KTB RACK BILATERAL",
        "AGACHAMENTO OVERHEAD KTB BILATERAL",
        "AGACHAMENTO OVERHEAD BARRA"
    ]
};
