module.exports = {
    AFUNDO: [
        "AFUNDO",
        "AFUNDO HALTER BILATERAL",
        "AFUNDO HALTER UNILATERAL",
        "AFUNDO BARRA NAS COSTAS",
        "AFUNDO BARRA NA FRENTE",
        "AFUNDO OVERHEAD KTB UNILATERAL",
        "AFUNDO OVERHEAD KTB BILATERAL",
        "AFUNDO OVERHEAD BARRA",
        "AFUNDO 1 STEP",
        "AFUNDO 2 STEPS",
        "AFUNDO 1 STEP + HALTER BILATERAL",
        "AFUNDO 1 STEP + HALTER UNILATERAL",
        "AFUNDO 2 STEPS + HALTER BILATERAL",
        "AFUNDO 2 STEPS + HALTER UNILATERAL"
    ],
    AVANCOS: [
        "AVANÇO",
        "AVANÇO + REVERSO"
    ],
    BULGARO: [
        "BÚLGARO GOBLET",
        "BÚLGARO + HALTER BILATERAL",
        "BÚLGARO + HALTER UNILATERAL",
        "BÚLGARO + BARRA HEXAGONAL",
        "BÚLGARO + BARRA NAS COSTAS"
    ]
};
