module.exports = [
    "AVIÃO",
    "ELEVAÇÃO UNI",
    "TERRA UNI",
    "PONTE UNILATERAL BANCO",
    "PONTE UNILATERAL CHAO",
    "ELEVAÇAO DE QUADRIL UNILATERAL CAIXA",
    "ELEVAÇAO DE QUADRIL UNILATERAL",
    "TERRA UNI HALTER BILATERAL",
    "TERRA UNI HALTER UNILATERAL",
    "TERRA UNI + POLIA UNILATERAL",
    "TERRA UNI + POLIA BILATERAL",
    "TERRA UNI BARRA HEXAGONAL",
    "TERRA UNI BARRA RETA",
    "STIFF HALTER UNILATERAL"
];
